### ISSUE TITLE
Ocultar entidade

### ISSUE THREAD

**Issue by superacesso** [gabrielbaltazar/gbswagger#12]
Por favor, qual anotação uso para que determinada entidade não seja exibida na parte de Models do swagger?

**Comment by gabrielbaltazar** [comment]
Bom dia...
Isso não é possível, pois se essa entidade está presente em algum Request ou Response da sua api, ela automaticamente vai aparecer no bloco de Models.

**Comment by superacesso** [comment]
Bom dia Gabriel,
Que essa entidade faz parte de outra entidade e fica mostrados a explicação dela dentro da entidade pai e nela.
Obrigado pelo retorno

**Comment by gabrielbaltazar** [comment]
Nesse caso você pode usar o atributo [SwagIgnore] na sua property que ela não vai pra documentação.
importante dar uses no atributo GBSwagger.Model.Attributes

**Comment by ds-sampaio** [comment]
É possivel aparecer uma property para o post por exemplo e para o get não aparecer?
tenho uma property q é um objeto de uma classe porém so deveria aparecer no post.

**Comment by gabrielbaltazar** [comment]
Você pode colocar a propriedade como WriteOnly usando a seguinte anotação.
[SwagProp(False, False, True)]

**Comment by ds-sampaio** [comment]
Gabriel, não funcionou dessa forma q vc me mostrou, qual a classe que faz essa verificação?
