### ISSUE TITLE
Mais de um uri Params

### ISSUE THREAD

**Issue by zottis** [gabrielbaltazar/gbswagger#13]
Olá,  Parabéns pelo middleware, excelente!!!!!
a minha dúvida é:
tem como declarar mais de um uri Params?
tentei de várias formas, mas não consegui.
Só consegui com o queryParams, mas achei deselegante, pois ele será obrigatório

 [SwagPath('rotas', 'Rotas')]
   TControllerRota = class
   private
     FRequest  : THorseRequest;
     FResponse : THorseResponse;
   public
     [SWagGET('{dataini}','Lista de Rotas quando data de Atualização entre :aDataI e :aDataF')]
     [SwagDate('dd-MM-yyyy')]
     [SwagParamPath('dataini','Data Atualização pelo periodo (Formato "dd-mm-yyyy|dd-mm-yyyy")')]
      [SwagDate('dd-MM-yyyy')]
     [SwagParamPath('datafim','Data Atualização fim (Formato "dd-mm-yyyy")')]

**Comment by gabrielbaltazar** [comment]
Bom dia, dá sim. Você só precisa colocar entre chaves o que é path param
[SWagGET('{dataini}/{datafim}','Lista de Rotas quando data de Atualização entre :aDataI e :aDataF')]

**Comment by zottis** [comment]
Deu certo, obrigado!!!!
