### ISSUE TITLE
Erro ao visualizar o swagger como página html 

### ISSUE THREAD

**Issue by aesjunior2707** [gabrielbaltazar/gbswagger#14]
Olá, Tudo bem ? 

Atualizei o middleware para nova versão e estou com um problema ao abrir a página html do swagger que é gerado,  porém quando coloco o parâmetro da URL como JSON  funciona corretamente.

![image](https://user-images.githubusercontent.com/54411625/170308135-ae4d6606-d9d3-41f2-ac68-0925abedb922.png)
![image](https://user-images.githubusercontent.com/54411625/170308213-e520ee9c-0905-4012-bb3b-2fd6592c1dbc.png)

**Comment by gabrielbaltazar** [comment]
Está conectado na internet?

**Comment by gabrielbaltazar** [comment]
Rode um exemplo simples que está na pasta Samples pra ver se o erro persiste

**Comment by aesjunior2707** [comment]
Bom dia, segue print com o exemplo simples rodando e o erro no console. 
Obrigado!
![image](https://user-images.githubusercontent.com/54411625/170488131-7442e4c4-c734-492b-b028-83337f8569ed.png)

**Comment by gabrielbaltazar** [comment]
Bom dia, Bug corrigido na versão 3.0.6.
Atualize por favor.
