### ISSUE TITLE
JSON com Array ao invés de Tipo

### ISSUE THREAD

**Issue by zottis** [gabrielbaltazar/gbswagger#15]
Olá
Tenho uma classe que tem um campo que é um array de outra classe, não estou conseguindo fazer aparecer no Swagger.
tentei colocar no  SwagParamBody

 [SwagParamBody('MTR', TMtrSet)]
 [SwagParamBody('Imagens', TImagemSet, 'Array de TImagem', True, false)]
 [SwagParamBody('Rastros', TRastroSet)]

mas nem aparece a opção de Setar a   TArrImagensSet e   TArrRastroSet
Minhas Classes

  TImagemSet = class;
  TArrImagensSet = array of TImagemSet;

  TRastroSet = class;
  TArrRastroSet = array of TRastroSet;

 TMtrSet = class
  private
    Fcd_mtr: Integer;
    Far_imagens  : TArrImagensSet;
    Far_rastros  : TArrRastroSet;
    Fcd_ordemcoleta : Integer;
  public
  
  Poderia me ajudar?

**Comment by gabrielbaltazar** [comment]
Conseguiu? 
Iria sugerir que usasse o TObjectList na property ar_imagens na classe TMtrSet

**Comment by zottis** [comment]
> 

Sim, 
Usei ao invés de um array de TImagemSet a Própria Classe
    [SwagClass('Array de TImagemSet)')]
    [SwagProp('Array de TImagemSet')]
    property ar_imagens         : TImagemSet read Far_imagens write Far_imagens;

    [SwagClass('Array de TRastroSet)')]
    [SwagProp('Array de TRastroSet')]
    property ar_rastros         : TRastroSet  read Far_rastros write Far_rastros;

e na documentação apareceu assim:
qt_latitude	string
qt_longitude	string
Array de TImagemSet	{
description:	
ImagemSet

qt_latitude	string
qt_longitude	string
dt_cadastro	string
ds_base64	string
ds_tipo	string
ds_nomearq	string
}
Array de TRastroSet	{
description:	
RastroSet

cd_rota	integer
cd_mtr	integer
dt_cadastro	string
hr_cadastro	string
tp_cadastro*	string
Cadastra os "Rastros" da coleta (Tipos:[FECHADO/PESO_ZERO/FINALIZADO])

qt_latitude	string
qt_longitude	string
}

e Obrigado pelo retorno
