### ISSUE TITLE
Undeclared identifier: 'AddCallbacks'

### ISSUE THREAD

**Issue by fgom-dev** [gabrielbaltazar/gbswagger#17]
Ao adicionar o middleware ao horse está apresentando o erro "Undeclared identifier: 'AddCallbacks'" na unit Horse.GBSwagger.Register na procedure "THorseGBSwaggerRegister.RegisterMethod" Linha 117.

**Comment by gabrielbaltazar** [comment]
Você tem que usar o Horse 3.0

**Comment by fgom-dev** [comment]
> Você tem que usar o Horse 3.0

Me desculpe por isso, vou tentar aqui

**Comment by gabrielbaltazar** [comment]
Conseguiu?
