### ISSUE TITLE
Anotações [SwagSecurityBearer()]  [SwagSecurityBasic()] não surtem efeito no swagger

### ISSUE THREAD

**Issue by arvanus** [gabrielbaltazar/gbswagger#18]
Olá, estou montando um projeto que usa autenticação nas rotas, porém aparentemente  o Swagger configurado no modelo de anotações não entende o uso dessas duas tags.
Poderiam dar uma ajuda?
Obrigado

**Comment by gabrielbaltazar** [comment]
Boa tarde. 
Veja os exemplos na pasta Samples\Horse\auth
Ali estamos usando essas anotaçãoes mencionadas.
Grato

**Comment by arvanus** [comment]
Certo, resolvido obrigado!
