### ISSUE TITLE
Adicionar a propriedade DocExpansion do Swagger

### ISSUE THREAD

**Issue by andrewsbejatto** [gabrielbaltazar/gbswagger#21]
Gostaria de adicionar a propriedade DocExpansion do Swagger nas configurações do GBSwagger.
Essa propriedade permite carregar a pagina da doc da API toda expandida, sem expandir ou só os métodos.

Segue o link da programação que fiz pelo meu git:
https://github.com/andrewsbejatto/gbswagger/commit/5e7151695a76d7bdc09911290fd6e132594ebe11

**Comment by andrewsbejatto** [comment]
Acabei de criar, verifica fazendo favor se foi certo.

**Comment by gabrielbaltazar** [comment]
Obrigado, já subi suas alterações.

**Comment by andrewsbejatto** [comment]
Obrigado Gabriel.
