### ISSUE TITLE
Swagger nao esta autenticando as rotas

### ISSUE THREAD

**Issue by maskcg** [gabrielbaltazar/gbswagger#23]
Boa Tarde, alguem pode me dar uma luz,
Tô passando para o swagger para autenticar as rotas conforme a imagem
porem ao testar a api, as rotas estao sem autenticacao
Quando rodo a documentacao, aparece o botao authorize, faco login, mais as rotas ficam desprotegidas do mesmo jeito!
fiz um teste colocando THorse.Use(HorseBasicAuthentication)
dessa forma as rotas ficam protegidas
![image](https://user-images.githubusercontent.com/56465194/199785630-d13c7d5c-4e4a-4bd9-b8dd-8f013a39445d.png)

na documentacao aparece as rotas assim:
![image](https://user-images.githubusercontent.com/56465194/199785921-87480eb7-8adf-400a-912e-06283dbac422.png)
![image](https://user-images.githubusercontent.com/56465194/199786079-a1670033-f59c-4b41-95c7-a0dfbcd40c61.png)

tentei usar o postman para testar, e por la tambem deixa executa o endpoint, qualquer usuario e senha que passo nao valida

**Comment by gabrielbaltazar** [comment]
Bom dia... Onde está sendo invocado esse Registry e onde você está registrando a rota de User?
É importante que esse trecho onde você chama o AddBasicSecurity seja invocado antes de registrar as suas rotas do User
