### ISSUE TITLE
Problema ao criar o html no Seattle.

### ISSUE THREAD

**Issue by pancary** [gabrielbaltazar/gbswagger#25]
![photo_4911446397950209860_y](https://user-images.githubusercontent.com/2369981/223096215-72543697-9851-4543-ab30-15c20d88661c.jpg)
![photo_4911446397950209856_x](https://user-images.githubusercontent.com/2369981/223096240-5591a421-5790-4695-b028-888eda350b59.jpg)

**Comment by gabrielbaltazar** [comment]
Bom dia, Bug corrigido na versão 3.0.6.
Atualize por favor.
