### ISSUE TITLE
/swagger/doc/json   parse error 

### ISSUE THREAD

**Issue by freitasjca** [gabrielbaltazar/gbswagger#36]
Usando gbswagger + horse  e  acedendo à página de documentação gerada pelo  gbswagger  (  http://localhost:9030/swagger/doc/html ), que estava bem ,  agora  tem erro na apresentação da página :

"Errors
Hide
 
Parser error on line 283
duplicated mapping key

Unable to render this definition
The provided definition does not specify a valid version field.

Please indicate a valid Swagger or OpenAPI version field. Supported version fields are swagger: "2.0" and those that match openapi: 3.x.y (for example, openapi: 3.1.0). 
"
Verifico em debug no
Horse.GBSwagger
procedure SwaggerJSON(ARequest: THorseRequest; AResponse: THorseResponse; ANext: TProc);

que o JSONSwagger enviado tem  "swagger": "2.0"  . Já não é suportada essa  versão?
Foi alterado o formato do JSON ?

![gbswagger](https://github.com/gabrielbaltazar/gbswagger/assets/77814796/9a2e0459-6d03-4d61-a8e8-8cda595ea6c2)

**Comment by freitasjca** [comment]
Já descobri 

Usando o https://editor.swagger.io/   para validar o JSON gerado no gbswagger , verifico que o problema era meu.
Tinha uma duplicação de um metodo Get

**Comment by gabrielbaltazar** [comment]
Exatamente, esse erro de duplicated mapping é quando tem 2 rotas iguais com o mesmo verbo.

**Comment by freitasjca** [comment]
Boa tarde Gabriel,

Obrigado pela sua resposta e obrigado por disponibilizar ferramentas como o
GBSwagger.

Queria-lhe perguntar, como devo fazer para ter projecto com  GBSwagger
para documentar a minha API  , mas com versões diferentes

  //V2
  Swagger
    .Config
      .Language('pt-BR')
    .&End
    .BasePath('api/v2')
    .Register
      .Response(204).Description('No Content').&End
      .Response(400).Description('Bad
Request').Schema(TFailureResponse).&End
      .Response(404).Description('Not Found').Schema(TFailureResponse).&End
      .Response(500).Description('Internal Server
Error').Schema(TFailureResponse).&End
    .&End
    .Info
......

//V3

Obrigado
João Freitas
