### ISSUE TITLE
Servidor linux

### ISSUE THREAD

**Issue by rafaeljeremias** [gabrielbaltazar/gbswagger#4]
Oi boa dia, primeiramente gostaria de parabenizar por sua iniciativa, gostei muito do projeto, porém estou com um probleminha se puder ajudar agradeço:

Desenvolvi um projeto e quando rodo no  windows funciona 100%, porém quando mando rodar no linux os endpoints aparecem assim:
â€‹/chamadoâ€‹/colaboradorâ€‹/historico

O que estou fazendo de errado, grato!

Rafael J Santos.

**Comment by gabrielbaltazar** [comment]
Bom dia.
Pode atualizar pra versão mais recente do Middleware e testar por favor.

**Comment by rafaeljeremias** [comment]
Bom dia, Obrigado Gabriel deu certo.

Em seg., 25 de abr. de 2022 às 09:12, Gabriel Baltazar <
***@***.***> escreveu:
