### ISSUE TITLE
Caractéres estranhos ao rodar no Delphi 10 Seattle

### ISSUE THREAD

**Issue by dfeprado** [gabrielbaltazar/gbswagger#5]
Boa tarde.

Conforme o título, caractéres estranhos surgem ao rodar no Delphi 10 Seattle.
![image](https://user-images.githubusercontent.com/47421907/135501811-baf47a02-273d-4806-a1af-477498dce123.png)

Essas são as respostas quando executado no Seattle:
![image](https://user-images.githubusercontent.com/47421907/135501886-8f984401-db18-4bdf-ae06-baaa66f0cfa9.png)
![image](https://user-images.githubusercontent.com/47421907/135501912-d71bac2a-5816-4b40-ab24-4a1bde85f6db.png)

E essas são as respostas quando executado no Rio:
![image](https://user-images.githubusercontent.com/47421907/135501949-cf72f6d8-ee4e-4f6a-a4a3-3e719cabef84.png)
![image](https://user-images.githubusercontent.com/47421907/135501961-09240e69-186d-4d49-a08d-79b49ef81bc5.png)

> Entenda **executado** como _compilado e executado_

Eu fucei o código e consegui alterar a resposta para possuir o charset UTF-8 no Seattle, e forcei o stream de resposta a usar o `TEncoding.UTF8`, mesmo assim os caracteres estranhos continuam.

**Comment by gabrielbaltazar** [comment]
Bom dia... Atualize o Middleware por favor.
